import Link from "next/link";

export const metadata = { title: "Terms of Service — The Third Eye" };

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background-base py-16 px-8">
      <div className="max-w-2xl mx-auto">
        <Link
          href="/"
          className="text-text-muted text-sm font-mono hover:text-text-secondary transition-colors"
        >
          ← The Third Eye
        </Link>

        <h1 className="font-display text-2xl font-semibold text-text-primary mt-8 mb-2">
          Terms of Service
        </h1>
        <p className="text-text-muted text-sm font-mono mb-10">Last updated: July 2026</p>

        <div className="space-y-8 text-text-secondary text-sm leading-relaxed">
          <section>
            <h2 className="text-text-primary font-semibold mb-2">Acceptance of Terms</h2>
            <p>
              By accessing or using The Third Eye, you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">The Service</h2>
            <p>
              The Third Eye is a self-hosted personal AI operating system intended for use by the
              account owner only. It provides an assistant, knowledge base, task management, and
              related productivity features.
            </p>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">Acceptable Use</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>Do not use the service for any unlawful purpose</li>
              <li>Do not attempt to gain unauthorized access to other accounts or systems</li>
              <li>You are responsible for the content you upload and the actions you take</li>
            </ul>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">Not Financial Advice</h2>
            <p>
              Any financial information generated by the assistant is for informational purposes
              only. The Third Eye is not a licensed financial advisor, and its outputs should not be
              relied upon as professional financial, legal, or tax advice.
            </p>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">Disclaimer of Warranties</h2>
            <p>
              The service is provided &quot;as is&quot; without warranties of any kind, either
              express or implied. We do not guarantee that the service will be uninterrupted,
              error-free, or that AI-generated content will be accurate.
            </p>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, the operator of the service shall not be liable
              for any indirect, incidental, or consequential damages arising from your use of the
              service.
            </p>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">Changes to These Terms</h2>
            <p>
              These terms may be updated from time to time. Continued use of the service after
              changes take effect constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">Privacy</h2>
            <p>
              Your use of the service is also governed by our{" "}
              <Link href="/privacy_policy" className="text-accent-blue hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-text-primary font-semibold mb-2">Contact</h2>
            <p>
              For any questions about these terms, contact{" "}
              <a
                href="mailto:anchit.tandon@gmail.com"
                className="text-accent-blue hover:underline"
              >
                anchit.tandon@gmail.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
