// Universal music knowledge base.
//
// A curated map of genres across the world and through the decades. It is the
// grounding for the Musicologist agent: these ~50 anchors cover the major
// families (electronic, hip-hop, pop, rock, jazz/blues/soul, classical, folk/
// country, and world traditions), and the agent reasons over both this data and
// its own training to cover the long tail — so the "knowledge base" is
// curated anchors + LLM reasoning, not a closed list.
//
// Reference artists are for STYLE grounding only (BPM/instrumentation/feel) —
// the pipeline never reproduces any artist's actual lyrics or melodies.

import type { GenreProfile, MusicInput } from "./types";

export const GENRE_KB: GenreProfile[] = [
  // ── Electronic ───────────────────────────────────────────────────────────
  { name: "House", aka: ["house music"], region: "Chicago → Global", era: "1980s–present", bpm: [118, 128], instruments: ["four-on-the-floor kick", "hi-hats", "synth stabs", "sampled vocals", "piano"], structure: "Intro - build - drop - breakdown - build - drop - outro", moods: ["uplifting", "groovy", "warm"], vocalStyle: "soulful hooks or chopped vocal samples", artists: ["Frankie Knuckles", "Disclosure", "Kaytranada"], production: "Warm analog kick, swung hats, filtered disco/soul samples, sidechain pump." },
  { name: "Deep House", region: "Global", era: "1990s–present", bpm: [118, 124], instruments: ["deep sub bass", "Rhodes", "pads", "soft kick"], structure: "Long intro - groove - subtle build - groove - outro", moods: ["chill", "sensual", "late-night"], vocalStyle: "smooth, reverbed vocal snippets", artists: ["Larry Heard", "Disclosure"], production: "Muted chords, deep bass, spacious reverb, restrained drops." },
  { name: "Tech House", region: "UK/Global", era: "1990s–present", bpm: [122, 128], instruments: ["punchy kick", "rolling bassline", "percussion", "vocal chops"], structure: "DJ-tool intro - groove - drop - break - drop", moods: ["hypnotic", "energetic"], vocalStyle: "short vocal chops", artists: ["Fisher", "Green Velvet"], production: "Tight low-end, minimal melody, groove-first, club-ready." },
  { name: "Techno", region: "Detroit → Berlin", era: "1980s–present", bpm: [125, 140], instruments: ["driving kick", "analog synths", "industrial percussion", "drones"], structure: "Hypnotic loop evolution, gradual layering, long builds", moods: ["dark", "hypnotic", "relentless"], vocalStyle: "instrumental or sparse processed vox", artists: ["Jeff Mills", "Charlotte de Witte"], production: "Repetitive, machine-driven, heavy reverb, warehouse atmosphere." },
  { name: "Hard Techno", aka: ["hardtechno", "hard techno"], region: "Europe", era: "1990s–present", bpm: [145, 160], instruments: ["distorted kick", "acid lines", "sirens", "hard percussion"], structure: "Fast relentless loops, sharp builds, aggressive drops", moods: ["aggressive", "intense", "euphoric"], vocalStyle: "instrumental or shouted stabs", artists: ["I Hate Models", "Sara Landry"], production: "Overdriven kicks, screeching acid, high energy, no let-up." },
  { name: "Acid", aka: ["acid techno", "acid house"], region: "Chicago/UK", era: "1980s–present", bpm: [120, 150], instruments: ["TB-303 acid bassline", "drum machine", "resonant squelch"], structure: "Evolving 303 patterns over driving drums", moods: ["trippy", "hypnotic", "psychedelic"], vocalStyle: "instrumental", artists: ["Phuture", "Hardfloor"], production: "Squelchy resonant 303 filter sweeps, 808/909 drums, raw energy." },
  { name: "Trance", region: "Germany → Global", era: "1990s–present", bpm: [130, 140], instruments: ["supersaw leads", "arpeggios", "pads", "rolling bass"], structure: "Intro - build - euphoric breakdown - drop - outro", moods: ["euphoric", "uplifting", "emotional"], vocalStyle: "ethereal female vocals or instrumental", artists: ["Armin van Buuren", "Above & Beyond"], production: "Layered supersaws, long emotional breakdowns, big anthemic drops." },
  { name: "Psytrance", aka: ["psy", "psychedelic trance", "goa", "psy acid"], region: "Goa, India → Global", era: "1990s–present", bpm: [140, 150], instruments: ["rolling 16th bassline", "psychedelic FX", "arpeggios", "acid lines"], structure: "Driving continuous groove, layered psychedelic builds", moods: ["psychedelic", "trippy", "hypnotic", "intense"], vocalStyle: "instrumental or spoken samples", artists: ["Infected Mushroom", "1200 Micrograms"], production: "Fast rolling bass, squelchy acid, alien FX, night-vs-forest energy." },
  { name: "Drum and Bass", aka: ["dnb", "d&b", "jungle"], region: "UK", era: "1990s–present", bpm: [160, 176], instruments: ["breakbeats", "heavy sub bass", "amen breaks", "reese bass"], structure: "Intro - breakbeat drop - halftime break - drop", moods: ["energetic", "dark", "rolling"], vocalStyle: "ragga/MC or instrumental", artists: ["Goldie", "Netsky"], production: "Chopped breakbeats, deep sub, fast tempo with halftime feel." },
  { name: "Dubstep", region: "UK", era: "2000s–present", bpm: [138, 145], instruments: ["wobble bass", "sub bass", "halftime drums", "growls"], structure: "Build - drop (bass wobble) - break - drop", moods: ["heavy", "dark", "aggressive"], vocalStyle: "vocal chops or instrumental", artists: ["Skrillex", "Excision"], production: "Halftime feel, modulated wobble/growl bass, big drops." },
  { name: "Ambient", region: "Global", era: "1970s–present", bpm: [50, 90], instruments: ["pads", "field recordings", "drones", "soft textures"], structure: "Evolving textures, no fixed sections, slow morph", moods: ["calm", "meditative", "spacious", "ethereal"], vocalStyle: "instrumental or wordless vocals", artists: ["Brian Eno", "Aphex Twin (Selected Ambient)"], production: "Long evolving pads, generous reverb, minimal or no percussion." },
  { name: "Synthwave", aka: ["retrowave", "outrun"], region: "Global", era: "2010s–present", bpm: [80, 118], instruments: ["analog synths", "gated reverb drums", "arpeggios", "bass synth"], structure: "Intro - verse - chorus - synth solo - outro", moods: ["nostalgic", "cinematic", "night-drive"], vocalStyle: "dreamy vocals or instrumental", artists: ["Kavinsky", "The Midnight"], production: "80s analog synths, neon nostalgia, gated snare, retro-futuristic." },
  { name: "Lo-fi Hip Hop", aka: ["lofi", "chillhop", "lo-fi", "lofi hip hop"], region: "Global", era: "2010s–present", bpm: [70, 90], instruments: ["dusty piano/Rhodes", "boom-bap drums", "vinyl crackle", "jazz samples"], structure: "Loop-based, relaxed, minimal variation", moods: ["chill", "cozy", "nostalgic", "study"], vocalStyle: "instrumental or soft samples", artists: ["Nujabes", "J Dilla"], production: "Lo-fi warmth, vinyl noise, swung drums, mellow jazz chords." },

  // ── Hip-hop / Rap ──────────────────────────────────────────────────────────
  { name: "Boom Bap", aka: ["boom-bap", "90s hip hop"], region: "New York", era: "late 1980s–1990s", bpm: [85, 95], instruments: ["punchy kick+snare", "soul/jazz samples", "scratches", "upright bass"], structure: "Intro - verse - hook - verse - hook - outro", moods: ["gritty", "confident", "nostalgic"], vocalStyle: "rhythmic rap, punchlines", artists: ["DJ Premier", "Nas"], production: "Hard-hitting sampled drums, chopped soul loops, vinyl grit." },
  { name: "Trap", region: "Atlanta → Global", era: "2000s–present", bpm: [130, 150], instruments: ["808 bass", "rapid hi-hat rolls", "snappy snares", "dark synths"], structure: "Intro - hook - verse - hook - verse - hook", moods: ["dark", "hard", "hypnotic"], vocalStyle: "melodic rap, ad-libs, autotune", artists: ["Metro Boomin", "Travis Scott"], production: "Booming 808s, triplet hats, sparse dark melodies, half-time feel." },
  { name: "Drill", region: "Chicago/UK", era: "2010s–present", bpm: [140, 145], instruments: ["sliding 808s", "dark piano/bells", "syncopated hats"], structure: "Hook - verse - hook, menacing groove", moods: ["menacing", "cold", "aggressive"], vocalStyle: "deadpan aggressive rap", artists: ["Pop Smoke", "Central Cee"], production: "Sliding 808 glides, sinister melodies, off-beat hi-hats." },
  { name: "G-Funk", region: "West Coast USA", era: "1990s", bpm: [90, 100], instruments: ["whining synth lead", "funk bass", "talkbox", "smooth drums"], structure: "Verse - hook - verse - hook, laid-back groove", moods: ["laid-back", "sunny", "smooth"], vocalStyle: "melodic West-Coast rap + sung hooks", artists: ["Dr. Dre", "Warren G"], production: "P-funk synth leads, deep bass, cruising tempo." },

  // ── Pop ───────────────────────────────────────────────────────────────────
  { name: "Pop", region: "Global", era: "1950s–present", bpm: [100, 130], instruments: ["vocals", "synths", "drums", "bass", "guitar"], structure: "Verse - pre-chorus - chorus - verse - chorus - bridge - chorus", moods: ["catchy", "upbeat", "emotional"], vocalStyle: "clear lead vocals with big hooks", artists: ["Max Martin productions", "Dua Lipa"], production: "Polished, hook-forward, tight arrangement, radio-ready mix." },
  { name: "Dance-Pop", aka: ["electropop", "dance pop"], region: "Global", era: "1980s–present", bpm: [118, 128], instruments: ["four-on-floor", "synths", "bright leads", "vocal hooks"], structure: "Verse - build - chorus/drop - verse - chorus", moods: ["energetic", "euphoric", "fun"], vocalStyle: "belted pop vocals", artists: ["Robyn", "Lady Gaga"], production: "Club-leaning pop, big synth choruses, sidechain, glossy." },
  { name: "K-Pop", region: "South Korea", era: "2000s–present", bpm: [100, 140], instruments: ["hybrid synths", "trap/EDM drums", "orchestral hits", "guitar"], structure: "Multi-section: intro - verse - pre - chorus - dance break - bridge - chorus", moods: ["energetic", "polished", "dynamic"], vocalStyle: "rap + sung, tight group harmonies", artists: ["BTS productions", "NewJeans"], production: "Genre-blending, abrupt section switches, maximalist, immaculate mix." },
  { name: "Hyperpop", region: "Global", era: "2010s–present", bpm: [140, 170], instruments: ["distorted synths", "pitched vocals", "glitch drums", "heavy bass"], structure: "Short, chaotic, maximal hooks", moods: ["hyper", "playful", "abrasive"], vocalStyle: "pitched/auto-tuned vocals", artists: ["100 gecs", "SOPHIE"], production: "Overloaded, clipped, pitched-up, maximalist digital chaos." },
  { name: "City Pop", region: "Japan", era: "late 1970s–1980s", bpm: [95, 120], instruments: ["funky bass", "electric piano", "clean guitar", "brass"], structure: "Verse - chorus - solo - chorus", moods: ["breezy", "urban", "nostalgic"], vocalStyle: "smooth Japanese/English vocals", artists: ["Tatsuro Yamashita", "Mariya Takeuchi"], production: "Glossy 80s funk-pop, lush chords, cruising sophistication." },

  // ── Rock / Metal ───────────────────────────────────────────────────────────
  { name: "Rock", aka: ["classic rock"], region: "US/UK", era: "1950s–present", bpm: [100, 140], instruments: ["electric guitars", "bass", "drums", "vocals"], structure: "Intro - verse - chorus - verse - chorus - solo - chorus", moods: ["energetic", "anthemic", "raw"], vocalStyle: "powerful lead vocals", artists: ["Led Zeppelin", "Foo Fighters"], production: "Driving guitars, live drums, big choruses, guitar solos." },
  { name: "Indie Rock", aka: ["indie", "alternative"], region: "US/UK", era: "1980s–present", bpm: [110, 150], instruments: ["jangly/fuzzy guitars", "bass", "drums"], structure: "Verse - chorus - verse - chorus - bridge", moods: ["earnest", "melodic", "lo-fi warmth"], vocalStyle: "characterful, often understated vocals", artists: ["The Strokes", "Arctic Monkeys"], production: "Guitar-forward, slightly raw, melodic, band-in-a-room energy." },
  { name: "Punk", aka: ["punk rock"], region: "US/UK", era: "1970s–present", bpm: [150, 200], instruments: ["distorted power chords", "fast drums", "bass"], structure: "Short, fast, verse-chorus, minimal solos", moods: ["aggressive", "rebellious", "raw"], vocalStyle: "shouted/snarled vocals", artists: ["Ramones", "Green Day"], production: "Fast, loud, distorted, minimal polish, high energy." },
  { name: "Metal", aka: ["heavy metal", "thrash", "death metal"], region: "Global", era: "1970s–present", bpm: [100, 200], instruments: ["heavily distorted guitars", "double-kick drums", "growls/screams", "bass"], structure: "Riff-driven, verse - chorus - breakdown - solo", moods: ["heavy", "aggressive", "epic", "dark"], vocalStyle: "clean, screamed, or growled", artists: ["Metallica", "Gojira"], production: "Palm-muted riffs, tight double-kick, wall-of-sound, heavy mix." },
  { name: "Shoegaze", region: "UK", era: "late 1980s–present", bpm: [90, 130], instruments: ["walls of reverbed guitar", "dreamy vocals", "bass", "drums"], structure: "Dense texture, verse-chorus buried in fuzz", moods: ["dreamy", "hazy", "melancholic"], vocalStyle: "soft vocals blended into the mix", artists: ["My Bloody Valentine", "Slowdive"], production: "Layered guitar noise, heavy reverb/delay, blurred wall of sound." },

  // ── Jazz / Blues / Soul / Funk ─────────────────────────────────────────────
  { name: "Jazz", aka: ["bebop", "swing"], region: "US", era: "1900s–present", bpm: [80, 200], instruments: ["upright bass", "brushed drums", "piano", "sax", "trumpet"], structure: "Head - improvised solos - trading - head", moods: ["sophisticated", "smoky", "expressive"], vocalStyle: "scat or crooned, or instrumental", artists: ["Miles Davis", "John Coltrane"], production: "Live acoustic feel, swing, improvisation, warm room tone." },
  { name: "Smooth Jazz", aka: ["jazz fusion", "nu jazz"], region: "US", era: "1970s–present", bpm: [80, 110], instruments: ["electric piano", "sax", "fretless bass", "soft drums"], structure: "Melodic head - tasteful solos - head", moods: ["relaxed", "sensual", "polished"], vocalStyle: "smooth vocals or instrumental", artists: ["Bob James", "GoGo Penguin (nu)"], production: "Glossy, mellow, melodic solos, laid-back groove." },
  { name: "Blues", region: "Mississippi Delta → US", era: "1900s–present", bpm: [60, 120], instruments: ["guitar", "harmonica", "piano", "upright/electric bass", "drums"], structure: "12-bar blues, call-and-response", moods: ["soulful", "melancholic", "raw"], vocalStyle: "emotive, bending vocals", artists: ["B.B. King", "Muddy Waters"], production: "Guitar bends, shuffle feel, vintage warmth, human imperfection." },
  { name: "Soul", aka: ["motown", "neo-soul"], region: "US", era: "1960s–present", bpm: [70, 110], instruments: ["organ", "horns", "bass", "drums", "backing vocals"], structure: "Verse - chorus - bridge, gospel-informed", moods: ["heartfelt", "warm", "uplifting"], vocalStyle: "powerful, gospel-rooted vocals", artists: ["Aretha Franklin", "D'Angelo (neo)"], production: "Live band warmth, horn stabs, tight rhythm section, emotive vocals." },
  { name: "Funk", region: "US", era: "1960s–present", bpm: [95, 120], instruments: ["slap bass", "wah guitar", "horns", "tight drums", "clavinet"], structure: "Groove-locked vamps, 'the one'", moods: ["funky", "danceable", "energetic"], vocalStyle: "chanted/soulful vocals", artists: ["James Brown", "Parliament-Funkadelic"], production: "Syncopated groove, tight pocket, punchy horns, emphasis on rhythm." },
  { name: "Disco", region: "US", era: "1970s", bpm: [110, 130], instruments: ["four-on-floor", "strings", "funky bass", "horns", "hi-hats"], structure: "Extended groove, string breaks, vocal hooks", moods: ["joyful", "danceable", "glamorous"], vocalStyle: "soulful lead + lush backing vocals", artists: ["Chic", "Donna Summer"], production: "Lush strings, four-on-floor, walking bass, glittery." },
  { name: "R&B", aka: ["rnb", "contemporary r&b"], region: "US", era: "1980s–present", bpm: [60, 100], instruments: ["smooth synths", "808/live drums", "bass", "keys"], structure: "Verse - pre - chorus, groove-led", moods: ["sensual", "smooth", "emotional"], vocalStyle: "melismatic, layered harmonies", artists: ["SZA", "The Weeknd"], production: "Silky pads, tasteful low-end, vocal stacks, intimate mix." },

  // ── Classical / Cinematic ──────────────────────────────────────────────────
  { name: "Classical", aka: ["orchestral", "baroque", "romantic"], region: "Europe", era: "1600s–1900s", bpm: [40, 160], instruments: ["strings", "woodwinds", "brass", "timpani", "piano"], structure: "Movements: exposition - development - recapitulation", moods: ["elegant", "dramatic", "sweeping"], vocalStyle: "instrumental or operatic", artists: ["Bach", "Beethoven"], production: "Full orchestra, dynamic contrast, acoustic hall reverb." },
  { name: "Cinematic", aka: ["film score", "epic", "trailer music"], region: "Global", era: "1930s–present", bpm: [60, 140], instruments: ["orchestra", "choir", "percussion", "hybrid synths", "braams"], structure: "Slow build - swell - climax - resolution", moods: ["epic", "emotional", "tense", "heroic"], vocalStyle: "choir or instrumental", artists: ["Hans Zimmer", "Ludwig Göransson"], production: "Orchestra + hybrid synths, big dynamics, huge percussion hits, tension." },
  { name: "Minimalism", aka: ["contemporary classical", "neoclassical"], region: "US/Europe", era: "1960s–present", bpm: [50, 120], instruments: ["piano", "strings", "subtle electronics"], structure: "Repeating cells that slowly evolve", moods: ["reflective", "hypnotic", "delicate"], vocalStyle: "instrumental", artists: ["Philip Glass", "Ólafur Arnalds"], production: "Repetitive motifs, gradual phasing, intimate acoustic recording." },

  // ── Folk / Country ─────────────────────────────────────────────────────────
  { name: "Folk", aka: ["singer-songwriter", "acoustic"], region: "Global", era: "traditional–present", bpm: [70, 120], instruments: ["acoustic guitar", "vocals", "harmonica", "fiddle", "banjo"], structure: "Verse - chorus, story-driven", moods: ["intimate", "earnest", "warm"], vocalStyle: "storytelling lead vocals", artists: ["Bob Dylan", "Bon Iver"], production: "Acoustic-forward, intimate, minimal, close-mic'd vocals." },
  { name: "Country", aka: ["americana", "bluegrass"], region: "US South", era: "1920s–present", bpm: [90, 140], instruments: ["acoustic/electric guitar", "pedal steel", "banjo", "fiddle", "bass"], structure: "Verse - chorus - verse - chorus - bridge", moods: ["heartfelt", "twangy", "nostalgic"], vocalStyle: "twangy narrative vocals", artists: ["Johnny Cash", "Chris Stapleton"], production: "Pedal steel, twangy guitars, storytelling, warm rootsy mix." },

  // ── World ──────────────────────────────────────────────────────────────────
  { name: "Afrobeats", aka: ["afropop", "afro-pop"], region: "Nigeria/Ghana → Global", era: "2000s–present", bpm: [100, 118], instruments: ["log drums/percussion", "synths", "bass", "vocal chops"], structure: "Groove-led verse - hook - verse - hook", moods: ["sunny", "danceable", "romantic"], vocalStyle: "melodic Afropop vocals, pidgin/English", artists: ["Burna Boy", "Wizkid"], production: "Syncopated percussion, bouncy groove, warm melodies, catchy hooks." },
  { name: "Afrobeat", region: "Nigeria", era: "1970s", bpm: [100, 130], instruments: ["horn section", "polyrhythmic percussion", "organ", "funk guitar", "bass"], structure: "Long grooves, extended horn/solo sections", moods: ["hypnotic", "political", "groovy"], vocalStyle: "call-and-response chants", artists: ["Fela Kuti"], production: "Extended polyrhythmic jams, tight horns, funk-jazz fusion." },
  { name: "Amapiano", region: "South Africa", era: "2010s–present", bpm: [108, 118], instruments: ["log drum bass", "airy pads", "jazzy piano", "shakers"], structure: "Slow-building groove, deep log-drum drops", moods: ["chill", "hypnotic", "soulful"], vocalStyle: "soulful vocal snippets or instrumental", artists: ["Kabza De Small", "DJ Maphorisa"], production: "Signature log-drum bass, spacious percussion, jazzy keys, deep groove." },
  { name: "Reggae", aka: ["dub", "dancehall"], region: "Jamaica", era: "1960s–present", bpm: [60, 90], instruments: ["offbeat skank guitar", "deep bass", "one-drop drums", "organ"], structure: "Verse - chorus, riddim-based", moods: ["laid-back", "conscious", "warm"], vocalStyle: "sung/toasted vocals, patois", artists: ["Bob Marley", "King Tubby (dub)"], production: "Offbeat skank, heavy bass, one-drop groove, spring reverb/echo (dub)." },
  { name: "Reggaeton", aka: ["latin urban"], region: "Puerto Rico → Global", era: "1990s–present", bpm: [90, 100], instruments: ["dembow rhythm", "808 bass", "synths", "vocal hooks"], structure: "Hook - verse - hook, dembow-driven", moods: ["danceable", "sensual", "energetic"], vocalStyle: "melodic Spanish rap/sung", artists: ["Daddy Yankee", "Bad Bunny"], production: "Dembow riddim, punchy 808s, catchy Latin hooks." },
  { name: "Latin Pop", aka: ["salsa", "bachata", "latin"], region: "Latin America", era: "1960s–present", bpm: [90, 130], instruments: ["nylon guitar", "brass", "congas/timbales", "piano montuno"], structure: "Verse - chorus - montuno/soneo", moods: ["romantic", "festive", "danceable"], vocalStyle: "passionate Spanish vocals", artists: ["Marc Anthony", "Shakira"], production: "Live Latin percussion, brass stabs, romantic melodies, danceable clave." },
  { name: "Bossa Nova", aka: ["samba", "brazilian"], region: "Brazil", era: "1950s–present", bpm: [100, 140], instruments: ["nylon guitar", "soft drums", "piano", "gentle percussion"], structure: "Verse - chorus, syncopated gentle groove", moods: ["smooth", "romantic", "breezy"], vocalStyle: "soft intimate Portuguese vocals", artists: ["João Gilberto", "Antônio Carlos Jobim"], production: "Syncopated nylon-guitar, brushed drums, warm intimate feel." },
  { name: "Bollywood", aka: ["filmi", "hindi film", "desi pop"], region: "India", era: "1950s–present", bpm: [90, 140], instruments: ["tabla", "dholak", "strings", "synths", "sitar/flute", "vocals"], structure: "Mukhda (hook) - antara (verse) - mukhda, dramatic", moods: ["romantic", "festive", "dramatic", "energetic"], vocalStyle: "expressive Hindi playback vocals", artists: ["A. R. Rahman", "Pritam"], production: "Fusion of Indian classical/folk instruments with pop/orchestral, lush and dramatic." },
  { name: "Bhangra", region: "Punjab, India", era: "1980s–present", bpm: [120, 145], instruments: ["dhol", "tumbi", "synths", "vocal chants"], structure: "High-energy groove - chant hook - verse", moods: ["festive", "high-energy", "celebratory"], vocalStyle: "energetic Punjabi vocals", artists: ["Panjabi MC"], production: "Driving dhol rhythm, tumbi riffs, big celebratory energy." },
  { name: "Hindustani Classical", aka: ["raga", "indian classical", "carnatic"], region: "India", era: "ancient–present", bpm: [40, 120], instruments: ["sitar", "tabla", "tanpura drone", "sarangi", "bansuri"], structure: "Alap (free) - jor - jhala - gat/bandish with tala", moods: ["meditative", "devotional", "intricate"], vocalStyle: "microtonal raga vocals or instrumental", artists: ["Ravi Shankar", "Hariprasad Chaurasia"], production: "Raga-based melody over tanpura drone, tala rhythmic cycles, improvisation." },
  { name: "Arabic Pop", aka: ["arabic", "khaleeji", "middle eastern"], region: "Middle East / North Africa", era: "traditional–present", bpm: [90, 130], instruments: ["oud", "qanun", "darbuka", "ney", "strings", "synths"], structure: "Maqam-based verse - chorus with rhythmic cycles", moods: ["passionate", "ornate", "danceable"], vocalStyle: "melismatic maqam vocals", artists: ["Amr Diab", "Umm Kulthum (classic)"], production: "Maqam scales, quarter-tones, darbuka groove, oud/qanun ornamentation." },
  { name: "Flamenco", region: "Andalusia, Spain", era: "1800s–present", bpm: [90, 200], instruments: ["nylon flamenco guitar", "palmas (handclaps)", "cajón", "vocals"], structure: "Compás-based palos (bulerías, soleá…)", moods: ["passionate", "fiery", "intense"], vocalStyle: "raw, ornamented cante vocals", artists: ["Paco de Lucía", "Camarón"], production: "Rapid guitar rasgueado, complex compás handclaps, deep emotion." },
  { name: "Celtic", aka: ["irish", "folk celtic"], region: "Ireland/Scotland", era: "traditional–present", bpm: [90, 130], instruments: ["fiddle", "tin whistle", "bodhrán", "uilleann pipes", "harp"], structure: "Jigs/reels, verse-chorus for songs", moods: ["lively", "wistful", "folkloric"], vocalStyle: "lilting folk vocals or instrumental", artists: ["The Chieftains", "Clannad"], production: "Fiddle/whistle melodies, bodhrán drive, acoustic warmth." },

  // ── Chill / Other ──────────────────────────────────────────────────────────
  { name: "Trip-Hop", aka: ["downtempo"], region: "Bristol, UK", era: "1990s–present", bpm: [70, 100], instruments: ["dusty breakbeats", "deep bass", "strings/samples", "vinyl noise"], structure: "Moody loop-based verse - hook", moods: ["moody", "cinematic", "smoky"], vocalStyle: "sultry, half-sung vocals", artists: ["Massive Attack", "Portishead"], production: "Slow breakbeats, dark samples, cinematic atmosphere, noir mood." },
  { name: "New Age", aka: ["meditation", "healing", "spa"], region: "Global", era: "1970s–present", bpm: [40, 80], instruments: ["soft synth pads", "nature sounds", "piano", "chimes", "flute"], structure: "Slow evolving, no strong sections", moods: ["calming", "serene", "healing", "spiritual"], vocalStyle: "wordless or gentle chants", artists: ["Enya", "Steven Halpern"], production: "Lush ambient pads, nature textures, very slow, deeply relaxing." },
];

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim();

/** Fuzzy-match the request's genre/subgenre text against the KB (name + aka). */
export function lookupGenres(input: MusicInput): GenreProfile[] {
  const hay = norm([input.genre, input.subgenre, input.description].filter(Boolean).join(" "));
  if (!hay) return [];
  const hits: { p: GenreProfile; score: number }[] = [];
  for (const p of GENRE_KB) {
    const names = [p.name, ...(p.aka ?? [])].map(norm);
    let score = 0;
    for (const n of names) {
      if (!n) continue;
      if (hay === n) score = Math.max(score, 3);
      else if (hay.includes(n) || n.includes(hay)) score = Math.max(score, 2);
      else if (n.split(" ").some((w) => w.length > 2 && hay.includes(w))) score = Math.max(score, 1);
    }
    if (score > 0) hits.push({ p, score });
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, 4).map((h) => h.p);
}

/** Compact grounding string the Musicologist agent reads before reasoning. */
export function knowledgeContext(input: MusicInput): string {
  const matches = lookupGenres(input);
  if (matches.length === 0) {
    return "No exact KB match — reason from your own knowledge of world music genres and eras.";
  }
  return matches.map((p) =>
    `• ${p.name}${p.aka?.length ? ` (aka ${p.aka.join(", ")})` : ""} — ${p.region}, ${p.era}. ` +
    `${p.bpm[0]}–${p.bpm[1]} BPM. Instruments: ${p.instruments.join(", ")}. ` +
    `Structure: ${p.structure}. Moods: ${p.moods.join(", ")}. Vocals: ${p.vocalStyle}. ` +
    `Production: ${p.production} Reference feel (do not copy): ${p.artists.join(", ")}.`
  ).join("\n");
}
